### ISSUE TITLE
cor_method argument missing in cor_df and collinear functions from version 2.0.0

### ISSUE THREAD

**Issue by marineReg** [BlasBenito/collinear#9]
Hello, 
I am very interested in your `collinear` package and am currently using the new version 2.0.0. I noticed that the `cor_method` argument, which allowed users to choose between `pearson` and `spearman`, no longer seems to be available in the `cor_df` and `collinear `functions`. I was wondering if there is a specific reason for this change. I checked the changelog but couldn’t find any explanation.
Thank you very much for your help

**Comment by BlasBenito** [comment]
Dear @marineReg, thank you for your question!

I removed the `cor_method` argument because Spearman correlation isn't suitable for multicollinearity analysis. Spearman's rank correlation only assesses whether one variable consistently increases or decreases with another, without capturing the strength of their linear relationship. Pearson's correlation, on the other hand, is designed to identify linear dependencies, making it the appropriate choice for detecting multicollinearity. 

I hope that helps answer your question.

Best wishes,

Blas
